name: visionzerobot

on:
  schedule:
    - cron: '33 17 * * Wed'
  workflow_dispatch: ~


jobs:
  visionzerobot-post:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_CONSUMER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_CONSUMER_ACCESS_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.13'
      - name: Install required packages
        run: mix deps.get
      - name: Set up secret file
        run: |
          echo $TWITTER_CONSUMER_API_KEY >> secrets.txt
          echo $TWITTER_CONSUMER_API_SECRET >> secrets.txt
          echo $TWITTER_ACCESS_TOKEN >> secrets.txt
          echo $TWITTER_ACCESS_TOKEN_SECRET >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
